version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    # ports:
    #   - "27017:27017"

    networks:
      - asp-mongodb-network


  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongodb-express
    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017
    
    networks:
      - asp-mongodb-network

networks:
  asp-mongodb-network:
    name: asp-mongodb-network
    external: true