version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - asp-mongodb-network

networks:
  asp-mongodb-network:
    name: asp-mongodb-network
    external: true
