version: '3.8'

services:
  mongodb-express:
    image: mongo-express
    restart: always
    container_name: mongodb-express
    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: P#ssw0rd
      ME_CONFIG_MONGODB_URL: mongodb://root:P#ssw0rd@mongodb:27017/
    
    networks:
      - asp-mongodb-network

networks:
  asp-mongodb-network:
    name: asp-mongodb-network
    external: true